apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yla9x8707-python 
  janus-idp.io/tekton: yla9x8707-python
  backstage.io/kubernetes-id: yla9x8707-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yla9x8707-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  