apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: yla9x8707-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yla9x8707-python 
  name: yla9x8707-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: yla9x8707-python
    weight: 100 
